allow for separate makemkv log
d-k-bo/python-makemkv pull request #4
Opened 2022-06-01 07:02 UTC by slick-nick-90

2022-06-01 11:22 UTC, d-k-bo commented
Thank you for your interest in contributing to this project!

Could you please explain why you think the parsing logic should be split into a separate method? I admit that `MakeMKV._run()` is a huge block of code, but I am not sure if this change is the right approach to solve the problem (the for loop is still ~200 lines long).

2022-06-02 02:52 UTC, slick-nick-90 commented on makemkv/types.py
> +    segment_map: str  # eg. "00021.mpls"
I wanted to be able to parse a makemkv log I already made. This change allows me to do that

2022-06-02 04:17 UTC, slick-nick-90 commented on makemkv/types.py
> +    segment_map: str  # eg. "00021.mpls"
good call, Fixed!

2022-06-03 22:47 UTC, d-k-bo requested changes
It would be great if you could also run [`nox`](https://nox.thea.codes/en/stable/tutorial.html#installation) on your code to fix formatting issues and try to fix linter warnings if there are any.

2022-06-03 22:47 UTC, d-k-bo commented on makemkv/makemkv.py
> +    def _parse_makemkv(self, lines, p=None) -> dict:
`_parse_makemkv_log` would be a more precise name.

Could you please provide type annotations? I think `lines` should be `Iterable[str]` (with `Iterable` being imported from `typing`). Return type should be `MakeMKVOutput`.

`p` can be ommited and all references should be replaced with `self.process`.

So the overall method signature would look like
```python
def _parse_makemkv_log(self, lines: Iterable[str]) -> MakeMKVOutput:
```

2022-06-03 22:47 UTC, d-k-bo commented on makemkv/makemkv.py
> +                if loglevel == logging.CRITICAL and p !=None:
To check if a value is None, `is` / `is not` should be used (see [PEP 8](https://peps.python.org/pep-0008/#programming-recommendations)), so this should be `if loglevel == logging.CRITICAL and self.process is not None:`.

2022-06-05 13:07 UTC, d-k-bo approved these changes

2022-06-05 13:12 UTC, d-k-bo requested changes

2022-06-05 13:12 UTC, d-k-bo commented on makemkv/makemkv.py
>                      p.kill()
This should be `self.process.kill()`

2022-06-05 13:12 UTC, d-k-bo commented on makemkv/makemkv.py
> +    def _parse_makemkv_log(self, lines: Iterable[str]) -> MakeMKVOutput:
`Iterable` needs to be imported in line 12

2022-06-05 19:23 UTC, d-k-bo commented
There are still issues with code formatting. Could you please run `nox -s format` or `black .` on your code?

2022-06-05 19:23 UTC, d-k-bo approved these changes

2022-06-06 00:27 UTC, slick-nick-90 commented
> It would be great if you could also run [`nox`](https://nox.thea.codes/en/stable/tutorial.html#installation) on your code to fix formatting issues and try to fix linter warnings if there are any.

I ran it and fixed it

2022-06-06 17:50 UTC, merged